apps/notifications/urls.py
from django.urls import path

from . import views

app_name = "notifications"

urlpatterns = [
    path("mark_as_read/<int:id>/", views.mark_as_read_view, name="mark_as_read"),
    path("mark_all_as_read/", views.mark_all_as_read_view, name="mark_all_as_read"),
    path("unread/", views.UnreadNotificationsListView.as_view(), name="unread"),
    path("", views.AllNotificationsListView.as_view(), name="all"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("apps.users.urls", namespace="users")),
    path("profiles/", include("apps.profiles.urls", namespace="profiles")),
    path("notifications/", include("apps.notifications.urls", namespace="notifications")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
    path("votes/", include("apps.votes.urls", namespace="votes")),
    path("", include("apps.questions.urls", namespace="questions")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

apps/notifications/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


class NotificationManager(models.query.QuerySet):
    """Notification manager"""

    def unread(self):
        """Returns query set of unread notifications"""
        qs = self.filter(is_read=False)
        return qs

    def mark_all_as_read(self):
        """Marks unread notifications as read and returns them"""
        qs = self.unread()
        qs.update(is_read=True)
        return qs


class Notification(models.Model):
    """Notification model"""

    from_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="sent_notifications",
    )
    to_user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="received_notifications",
    )
    created_at = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)
    sent = models.BooleanField(default=False)
    message = models.CharField(null=True, max_length=50)
    url = models.URLField(null=True)

    objects = NotificationManager.as_manager()

    class Meta:
        ordering = ["created_at"]

    def __str__(self) -> str:
        return self.message

    def mark_as_read(self) -> bool:
        self.is_read = True
        self.save()
        return True

    def to_json(self) -> dict:
        return {
            "to_user_username": self.to_user.username,
            "to_user_email": self.to_user.email,
            "message": self.message,
            "created_at": self.created_at.strftime("%Y-%m-%d %H:%m"),
            "url": self.url,
        }

apps/notifications/views.py
from django.http import HttpResponseRedirect
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.utils.decorators import method_decorator

from .models import Notification


@method_decorator(login_required, name="dispatch")
class NotificationsListView(ListView):
    template_name = "notifications/notifications.html"
    context_object_name = "notifications"
    paginate_by = 20


class AllNotificationsListView(NotificationsListView):
    def get_queryset(self) -> QuerySet[Notification]:
        notifications = self.request.user.received_notifications.all()
        return notifications


class UnreadNotificationsListView(NotificationsListView):
    def get_queryset(self) -> QuerySet[Notification]:
        notifications = self.request.user.received_notifications.unread()
        return notifications


@require_POST
@login_required
def mark_as_read_view(request, id: int) -> HttpResponseRedirect:
    notification = get_object_or_404(Notification, id=id, to_user=request.user)
    notification.mark_as_read()
    return redirect("notifications:unread")


@require_POST
@login_required
def mark_all_as_read_view(request) -> HttpResponseRedirect:
    request.user.received_notifications.mark_all_as_read()
    return redirect("notifications:unread")

templates/notifications/notifications.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-9">
    <div class="mt-3 p-3 d-flex flex-row border bg-light bg-gradient rounded">
        <div>
            <h2>Уведомления</h2>
        </div>
        <div class="px-3 d-flex flex-row">
            <form action="{% url 'notifications:all' %}">
                <button type="submit" class="btn btn-primary" data-mdb-ripple-color="dark">Все</button>
            </form>
            <form action="{% url 'notifications:unread' %}">
                <button type="submit" class="btn btn-primary" data-mdb-ripple-color="dark">Непрочитанные</button>
            </form>
            <form action="{% url 'notifications:mark_all_as_read' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" data-mdb-ripple-color="dark">Прочитать все</button>
            </form> 
        </div>
    </div>
    <div id="notification-list">
        {% for n in notifications %}
        <div class="card text-dark bg-light mb-3 mt-3">
            <div class="d-flex flex-row g-0">
                <div class="d-flex flex-column">
                    <a href="{{n.url}}">
                        <div class="p-3">
                            <h5 id="notification-message" class="card-title">{{ n.message }}</h5>
                        </div>
                    </a>
                    <div class="p-3 d-flex">
                        <p class="card-text">{{ n.created_at|date:"d-m-Y H:i" }}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div class="col-3">
    {% include 'layout/popular_tags.html' %}          
</div>


{% endblock %}