apps/questions/urls.py
from django.urls import path

from . import views


app_name = "questions"

urlpatterns = [
    path("", views.QuestionsListView.as_view(), name="home"),
    path(
        "questions/popular/", views.PopularQuestionsListView.as_view(), name="popular"
    ),
    path(
        "questions/by_tag/<slug:tag_slug>/",
        views.QuestionsByTagListView.as_view(),
        name="by_tag",
    ),
    path("questions/search/", views.question_search_view, name="search"),
    path("question/<int:pk>/<slug:slug>/", views.QuestionView.as_view(), name="detail"),
    path("question/create/", views.QuestionCreateView.as_view(), name="create"),
    path(
        "question/update/<int:pk>/", views.QuestionUpdateView.as_view(), name="update"
    ),
    path(
        "question/delete/<int:pk>/", views.QuestionDeleteView.as_view(), name="delete"
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("apps.users.urls", namespace="users")),
    path("profiles/", include("apps.profiles.urls", namespace="profiles")),
    path("notifications/", include("apps.notifications.urls", namespace="notifications")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
    path("votes/", include("apps.votes.urls", namespace="votes")),
    path("", include("apps.questions.urls", namespace="questions")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

apps/questions/models.py
from __future__ import annotations

from django.db import models
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from django.utils.text import slugify
from django.core.cache import cache

from taggit.managers import TaggableManager
from taggit.models import Tag
from apps.votes.models import Vote


class PublishedManager(models.Manager):
    """Published questions manager"""

    def get_queryset(self) -> models.QuerySet[Question]:
        """Returns query set of published questions"""
        return super().get_queryset().filter(draft=False)

    def get_all_questions(self) -> models.QuerySet[Question]:
        """Returns query set of all published questions"""
        queryset = (
            self.get_queryset()
            .select_related("author", "author__profile")
            .prefetch_related("tags")
            .annotate(
                likes_count=models.Count(
                    models.Case(
                        models.When(votes__vote=1, then=1),
                        output_field=models.IntegerField(),
                    )
                ),
                dislikes_count=models.Count(
                    models.Case(
                        models.When(votes__vote=-1, then=1),
                        output_field=models.IntegerField(),
                    )
                ),
            )
            .all()
        )
        return queryset

    def get_tagged_questions(self, tag: str) -> models.QuerySet[Question]:
        """Returns query set of all published questions tagged by `tag`"""
        tag = get_object_or_404(Tag, slug=tag)
        queryset = self.get_all_questions().filter(tags__in=[tag])
        return queryset

    def get_similar_questions(
        self, question: Question, limit: int = 4
    ) -> models.QuerySet[Question]:
        """Returns query set of published questions similar to a specific question"""
        cache_key = f"similar_questions_{question.id}"
        similar_questions = cache.get(cache_key)
        if similar_questions is None:
            question_tags_ids = question.tags.values_list("id", flat=True)
            similar_questions = (
                self.get_queryset()
                .filter(tags__in=question_tags_ids)
                .exclude(id=question.id)
                .annotate(same_tags=models.Count("tags"))
                .order_by("-same_tags", "-date_published")[:limit]
            )
            cache.set(cache_key, similar_questions, timeout=3600)
        return similar_questions

    def get_popular_questions(self, limit: int = None) -> models.QuerySet[Question]:
        """Returns query set of popular published questions"""
        if limit:
            return self.get_all_questions().order_by("-views", "-votes")[:limit]
        return self.get_all_questions().order_by("-views", "-votes")

    def get_popular_tags(self, limit: int = 10) -> models.QuerySet[Tag]:
        """Returns the most popular tags"""
        cache_key = "popular_tags_list"
        tags = cache.get(cache_key)
        if tags is None:
            tags = (
                Tag.objects.filter(question__draft=False)
                .annotate(total_questions=models.Count("question"))
                .order_by("-total_questions")[:limit]
            )
            cache.set(cache_key, tags, timeout=86400)
        return tags

    def get_question_answers(self, question: Question) -> models.QuerySet[Answer]:
        """Returns query set of answers for a specific question"""
        answers = (
            Answer.objects.filter(question=question, active=True)
            .select_related("author", "author__profile")
            .annotate(
                likes_count=models.Count(
                    models.Case(
                        models.When(votes__vote=1, then=1),
                        output_field=models.IntegerField(),
                    )
                ),
                dislikes_count=models.Count(
                    models.Case(
                        models.When(votes__vote=-1, then=1),
                        output_field=models.IntegerField(),
                    )
                ),
            )
        )
        return answers

    def search(self, query: str) -> models.QuerySet[Question]:
        lookup = models.Q(title__icontains=query) | models.Q(content__icontains=query)
        return self.get_all_questions().filter(lookup)


class Question(models.Model):
    """Question model"""

    title = models.CharField(
        max_length=25,
        help_text="Max length - 25 symbols.",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="questions",
    )
    votes = GenericRelation(Vote, related_query_name="questions")
    date_published = models.DateTimeField(default=timezone.now)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    content = models.TextField(max_length=5000)
    views = models.IntegerField(default=0)
    draft = models.BooleanField(default=False)
    slug = models.SlugField(max_length=50, blank=True)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-date_published"]
        indexes = [
            models.Index(fields=["-date_published", "author"]),
        ]

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self) -> str:
        return reverse("questions:detail", kwargs={"pk": self.pk, "slug": self.slug})

    def save(self, *args, **kwargs) -> None:
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class QuestionImages(models.Model):
    """Images attached to the question"""

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="questions_images/%Y/%m/%d/")


class Answer(models.Model):
    """Answer model"""

    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="answers",
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="answers",
    )
    votes = GenericRelation(Vote, related_query_name="answers")
    content = models.TextField(max_length=5000)
    date_published = models.DateField(auto_now_add=True)
    best_answer = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["-date_published"]
        indexes = [models.Index(fields=["-date_published", "author", "question"])]

    def __str__(self) -> str:
        return f"{self.author} gives an answer on {self.question}"

    def get_absolute_url(self) -> str:
        return reverse(
            "questions:detail",
            kwargs={"pk": self.question.pk, "slug": self.question.slug},
        )

apps/questions/forms.py
from django import forms

from .models import Answer, Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["title", "tags", "content", "draft"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = [
            "content",
        ]

apps/questions/views.py
from typing import Any

from django.db import models
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.utils.text import slugify
from django.urls import reverse
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Answer
from .forms import AnswerForm, QuestionForm
from .mixins import AuthorRequiredMixin


User = get_user_model()


class QuestionsListView(generic.ListView):
    template_name = "questions/index.html"
    queryset = Question.published.get_all_questions()
    context_object_name = "questions_list"
    paginate_by = 10
    page_title = "Last questions"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = self.page_title
        return context


class QuestionsByTagListView(QuestionsListView):
    page_title = "Questions tagged #"

    def get_queryset(self) -> QuerySet[Question]:
        tag_slug = self.kwargs.get("tag_slug")
        return Question.published.get_tagged_questions(tag_slug)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = f"{self.page_title}{self.kwargs.get('tag_slug')}"
        return context


class PopularQuestionsListView(QuestionsListView):
    queryset = Question.published.get_popular_questions()
    page_title = "Popular questions"


class QuestionDetailView(generic.DetailView):
    template_name = "questions/question_detail.html"
    model = Question
    context_object_name = "question"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = AnswerForm()
        question = self.get_object()
        context["answers"] = Question.published.get_question_answers(question)
        context["similar_questions"] = Question.published.get_similar_questions(
            question
        )
        return context


class AnswerFormView(generic.detail.SingleObjectMixin, generic.FormView):
    template_name = "questions/question_detail.html"
    form_class = AnswerForm
    model = Answer

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_queryset()
        return super().post(request, *args, **kwargs)


class QuestionView(generic.View):
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        view = QuestionDetailView.as_view()
        question_id = self.kwargs.get("pk")
        Question.objects.filter(pk=question_id).update(views=models.F("views") + 1)
        return view(request, *args, **kwargs)

    @method_decorator(login_required())
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        view = AnswerFormView.as_view()
        form = AnswerForm(request.POST)
        if form.is_valid():
            question = Question.objects.get(id=self.kwargs["pk"])
            form.instance.author = request.user
            form.instance.question = question
            form.save()
        return view(request, *args, **kwargs)


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "questions/question_create_form.html"
    form_class = QuestionForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        title = form.cleaned_data.get("title")
        form.instance.slug = slugify(title)
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        question = self.object
        return reverse(
            "questions:detail", kwargs={"pk": question.id, "slug": question.slug}
        )


class QuestionUpdateView(AuthorRequiredMixin, generic.UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = "questions/question_update_form.html"
    context_object_name = "question"

    def get_success_url(self) -> str:
        return self.get_object().get_absolute_url()


class QuestionDeleteView(AuthorRequiredMixin, generic.DeleteView):
    model = Question
    success_url = "/"
    context_object_name = "question"


@require_GET
def question_search_view(request: HttpRequest) -> HttpResponse:
    results = []
    page_title = "Questions search"
    query = request.GET.get("query")

    if query:
        results = Question.published.search(query)
        page_title = f"Questions that contain {query}."

    return render(
        request,
        "questions/index.html",
        context={"page_title": page_title, "questions_list": results},
    )

templates/questions/index.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-9">
    <div class="mt-3 p-3 d-flex border bg-light bg-gradient rounded">
        <div class="d-flex align-self-center">
            <h2>{{ page_title }}</h2>
        </div>
        <div class="ml-auto align-self-center">
            <a href="{% url 'questions:create' %}">
                <button type="button" class="btn btn-primary" data-mdb-ripple-color="dark">Задать вопрос</button>
            </a>
        </div>
    </div>
    {% include 'layout/questions.html' with questions=questions_list %}
</div>
<div class="col-3">
    {% include 'layout/popular_tags.html' %}          
</div>
{% endblock %}
   

templates/questions/question_confirm_delete.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 bg-light border border-1 rounded row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Удалить вопрос?</h2>
  <hr class="border border-2 border-danger">
  <p class="text-center">Вы действительно хотите удалить {{ object }}?</p>
  <form method="post" action="{% url 'questions:delete' question.pk %}">
    {% csrf_token %}
    <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn btn-danger btn-lg ms-2">Удалить</button>
    </div>
  </form>
</div>
{% endblock %}

templates/questions/question_create_form.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-3"></div>

<div class="mt-3 mb-3 p-3 col-6 bg-light rounded border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Задать вопрос</h2>
  <hr class="border border-2 border-primary">
  <form method="POST" action="{% url 'questions:create' %}">

    {% csrf_token %}

    <div class="form-outline mb-4">
      <label class="control-label">Название</label>
      <input class="form-control" name="title" type="text">
    </div>
      
    <div class="form-outline mb-4">
      <label class="control-label">Тэги (введите теги через запятую)</label>
      <input class="form-control"  name="tags" type="text">
    </div>
      
    <div class="form-floating mb-4">
        <textarea type="content" name="content" class="form-control" placeholder="Leave a comment here" id="floatingTextarea"></textarea>
        <label class="form-label" for="form3Example9">Введите вопрос</label>
    </div>

    <!--
      фотка
      <input type="file" class="form-control" id="customFile" />
      <label class="form-label" for="form3Example90">Upload avatar</label>
    -->
    <div class="d-flex justify-content-end pt-3">
      <button type="submit" class="btn btn-primary btn-lg ms-2" value="Complete Registration!">Задать вопрос</button>
    </div>
  </form>
  
</div>
{% endblock %}

templates/questions/question_detail.html
{% extends 'layout/base.html' %}
{% load questions_tags %}

{% block content %}
<div class="col-9">
  <div class="mt-3 bg-light p-2 row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="p-1 px-3 d-flex flex-column">
      <div class="p-2 d-flex justify-content-left">
        <h1>{{ question.title }}</h1>
      </div>

      <div class="d-flex flex-row text-muted justify-content-left">
        <div class="d-flex mx-2">
          <p>Просмотров - {{ question.views }}</p>
        </div>
        <div class="d-flex mx-2">
          <p>Опубликовано - {{ question.date_published|date:"d-m-Y H:i" }}</p>
        </div>
        <div class="d-flex mx-2">
          <p>Изменено - {{ question.date_updated|date:"d-m-Y H:i" }}</p>
        </div>
      </div>
      <hr style="margin-top: 0.1em; margin-bottom: 0.1em;">

      <div class="p-3 d-flex justify-content-left">
        <h6>{{ question.content }}</h6>
      </div>
      {% if request.user == question.author %}
      <div class="d-flex flex-row justify-content-end">
        <div class="d-flex align-items-start" style="padding: .8rem .2rem .0rem .6rem;">
          <form action="{% url 'questions:update' question.pk %}">
            <button class="btn btn-outline-warning" type="submit" data-mdb-ripple-color="dark" style="padding: .15rem .5rem .1rem; float: left;">
              Изменить
            </button>
          </form>
        </div>

        <div class="d-flex align-items-start" style="padding: .8rem .2rem .0rem .6rem;">
          <form action="{% url 'questions:delete' question.pk %}">
            {% csrf_token %}
            <button class="btn btn-outline-danger" type="submit" data-mdb-ripple-color="dark" style="padding: .15rem .5rem .1rem; float: left;">
              Удалить
            </button>
          </form>
        </div>
      </div>
      {% endif %}

      <div class="d-flex flex-row justify-content-left">
        {% for tag in question.tags.all %}
        <div class="d-flex align-items-start" style="padding: .8rem .2rem .0rem .6rem;">
            <form action="{% url 'questions:by_tag' tag.slug %}">
                <button class="btn btn-outline-primary" type="submit" data-mdb-ripple-color="dark" style="padding: .15rem .5rem .1rem; float: left;">
                    {{ tag.name }}
                </button>
            </form>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% include 'layout/answers.html' with answers=answers question=question %}

</div>

<div class="col-3">
  {% if similar_questions%}
    {% include 'layout/questions_side_menu.html' with questions=similar_questions %}
  {% else %}
    {% include 'layout/popular_tags.html' %}
  {% endif %}
</div>

{% endblock %}

templates/questions/question_update_form.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-3"></div>

<div class="mt-3 mb-3 p-3 col-6 bg-light rounded border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Изменить вопрос</h2>
  <hr class="border border-2 border-primary">
  <form method="POST" action="{% url 'questions:update' question.pk %}">

    {% csrf_token %}

    <div class="form-outline mb-4">
      <label class="control-label">Название</label>
      <input class="form-control" value="{{form.title.value}}" name="title" type="text">
    </div>
      
    <div class="form-outline mb-4">
      <label class="control-label">Тэги (введите теги через запятую)</label>
      <input class="form-control"  value="{% for tag in form.tags.value %}{{tag.name}}{% endfor %}" name="tags" type="text">
    </div>
      
    <div class="form-floating mb-4">
        <textarea type="content" name="content" class="form-control">{{form.content.value }}</textarea>
        <label class="form-label" for="form3Example9">Введите вопрос</label>
    </div>

    <!--
      фотка
      <input type="file" class="form-control" id="customFile" />
      <label class="form-label" for="form3Example90">Upload avatar</label>
    -->
    <div class="d-flex justify-content-end pt-3">
      <button type="submit" class="btn btn-primary btn-lg ms-2" value="Complete Registration!">Изменить</button>
    </div>
  </form>
  
</div>
{% endblock %}

templates/questions/search.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-9">
    <h2 class="mt-3 p-3 border bg-light rounded">
        {% with results.count as total_results %}
            Найдено вопросов {{ total_results }}
        {% endwith %}
        <button onclick="location.href=('{% url 'questions:question_create' %}')" type="button" class="btn btn-success " data-mdb-ripple-color="dark">Ask</button>
    </h2>
    {% include 'layout/questions.html' with questions=results %}
</div>
<div class="col-3">
    <div class="position-fixed">
        <h2 class="mt-3 p-3 border text-light bg-secondary rounded text-center" style="max-width: 20rem;">
            {% with results.count as total_results %}
                Найдено тегов {{ total_results }}
            {% endwith %}
        </h2>
    </div>
</div>
{% endblock %}