apps/users/urls.py
from django.urls import path
from django.contrib.auth import views
from django.urls import reverse_lazy

from .views import UserRegistrationView

app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password-change/",
        views.PasswordChangeView.as_view(
            success_url=reverse_lazy("users:password_change_done"),
            template_name="users/password_change_form.html",
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("apps.users.urls", namespace="users")),
    path("profiles/", include("apps.profiles.urls", namespace="profiles")),
    path("notifications/", include("apps.notifications.urls", namespace="notifications")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
    path("votes/", include("apps.votes.urls", namespace="votes")),
    path("", include("apps.questions.urls", namespace="questions")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """User model"""

    username = models.CharField(
        max_length=25,
        unique=True,
        help_text=(
            "Less then 25 characters. Only letters, digits and @/./+/-/_ symbols."
        ),
        error_messages={"unique": "This username is already used."},
    )
    email = models.EmailField(
        unique=True,
        error_messages={"unique": "This email is already used."},
    )
    send_messages = models.BooleanField(default=False)

    REQUIRED_FIELDS = ["email"]

    def __str__(self) -> str:
        return self.username

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.db import IntegrityError


User = get_user_model()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
            "send_messages",
        )

    def clean_username(self) -> str:
        username = self.cleaned_data.get("username")
        if " " in username:
            raise forms.ValidationError("Username can't contains spaces.")
        return username

    def clean_email(self) -> str:
        email = self.cleaned_data.get("email")
        if email and User.objects.filter(email=email):
            raise forms.ValidationError("This email is already used.")
        return email

    def clean_password2(self) -> str:
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 != password2:
            raise forms.ValidationError("Password mismatch!")
        return password2

    def save(self, commit: bool = True):
        user = super(UserCreationForm, self).save(commit=False)
        user.first_name = self.cleaned_data.get("first_name").capitalize()
        user.last_name = self.cleaned_data.get("last_name").capitalize()
        user.username = self.cleaned_data.get("username")
        user.email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password1")
        user.set_password(password)
        if commit:
            try:
                user.save()
            except IntegrityError:
                raise forms.ValidationError(
                    "User with this username or email already exists."
                )
        return user

apps/users/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.http import HttpResponse
from django.contrib.auth import get_user_model

from .forms import UserRegistrationForm


User = get_user_model()


class UserRegistrationView(FormView):
    template_name = "users/registration.html"
    model = User
    form_class = UserRegistrationForm

    def form_valid(self, form: UserRegistrationForm) -> HttpResponse:
        user = form.save()
        return render(
            self.request, "users/registration_done.html", context={"user": user}
        )

    def form_invalid(self, form: UserRegistrationForm) -> HttpResponse:
        return render(self.request, "users/registration.html", context={"form": form})

templates/users/login.html
{% extends 'layout/base.html' %}
{% load static %}
{% load bootstrap5 %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 bg-light border border-1 rounded row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Войти</h2>
  <hr class="border border-2 border-primary">
  <form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    
      <div class="form-outline mb-4">
        <label class="control-label">Никнейм</label>
        <input class="form-control" value="{{ form.login.value|default_if_none:'' }}" name="username" placeholder="" type="username">
      </div>

      <div class="form-outline mb-4">
        <label class="control-label">Пароль</label>
        <input class="form-control" name="password" placeholder="" type="password">
      </div>
        
      <div class="d-flex justify-content-end pt-3">
        <button type="submit" class="btn btn-primary btn-lg ms-2">Войти</button>
      </div>

      <input type="hidden" name="next" value="{{ next }}">

  </form>
  <p><a href="{% url 'users:password_reset' %}" class="href">Забыли пароль?</a></p>
</div>
{% endblock %}

templates/users/logout.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 bg-light rounded border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Вы вышли из аккаунта</h2>
  <hr class="border border-2 border-primary">
    <form action="{% url 'users:login' %}">
      <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn btn-primary btn-lg ms-2">Войти снова</button>
      </div>
    </form>
</div>
{% endblock %}

templates/users/password_change_done.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 rounded bg-light border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Смена пароля</h2>
  <hr class="border border-2 border-primary">
  <p>Ваш пароль был успешно изменен.</p>
    <form action="{% url 'users:login' %}">
      <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn btn-primary btn-lg ms-2">Войти</button>
      </div>
    </form>
</div>
{% endblock %}

templates/users/password_change_form.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 bg-light rounded border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <h2 class="text-center">Смена пароля</h2>
    <hr class="border border-2 border-primary">
    <p>Для смены пароля заполните форму:</p>
    <form method="post">
        {% csrf_token %}
        <div class="form-outline mb-4">
            <label class="control-label">Старый пароль</label>
            <input class="form-control" name="old_password" placeholder="" type="password">
            {% if 'old_password' in form.errors %}
            {% for error in form.old_password.errors %}
                <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}
        </div>

        <div class="form-outline mb-4">
            <label class="control-label">Новый пароль</label>
            <input class="form-control" name="new_password1" placeholder="" type="password">
            {% if 'new_password1' in form.errors %}
            {% for error in form.new_password1.errors %}
                <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}
        </div>
            
        <div class="form-outline mb-4">
            <label class="control-label">Повторите пароль</label>
            <input class="form-control" name="new_password2" placeholder="" type="password">
            {% if 'new_password2' in form.errors %}
            {% for error in form.new_password2.errors %}
                <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}
        </div>

        <div class="d-flex justify-content-end pt-3">
            <button type="submit" class="btn btn-primary btn-lg ms-2">Сменить</button>
        </div>
    </form>
{% endblock %}

templates/users/password_reset_complete.html
{% extends 'layout/base.html' %}

{% block content %}
 <div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 bg-light rounded border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Сброс пароля</h2>
  <hr class="border border-2 border-primary">
  <p>Ваш пароль был успешно изменен.</p>
    <form action="{% url 'users:login' %}">
      <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn btn-primary btn-lg ms-2">Войти</button>
      </div>
    </form>
</div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 rounded bg-light border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Смена пароля</h2>
  <hr class="border border-2 border-primary">
    {% if validlink %}
    <p>Введите новый пароль дважды:</p>
    <form method="post">
        {% csrf_token %}
        <div class="form-outline mb-4">
            <label class="control-label">Новый пароль</label>
            <input class="form-control" name="new_password1" placeholder="" type="password">
            {% if 'new_password1' in form.errors %}
            {% for error in form.new_password1.errors %}
                <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}
        </div>
            
        <div class="form-outline mb-4">
            <label class="control-label">Повторите пароль</label>
            <input class="form-control" name="new_password2" placeholder="" type="password">
            {% if 'new_password2' in form.errors %}
            {% for error in form.new_password2.errors %}
                <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            {% endif %}
        </div>

        <div class="d-flex justify-content-end pt-3">
            <button type="submit" class="btn btn-primary btn-lg ms-2">Сменить</button>
        </div>
    </form>
    {% else %}
    <p>Ссылка для смены пароля не валидна. Возможно, она уже была использована.</p>
    <p>Для смены пароля запросите новую ссылку.</p>
    {% endif %}
{% endblock %}

templates/users/password_reset_done.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>
<div class="mt-3 mb-3 p-3 col-4 rounded border bg-light border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Сброс пароля</h2>
  <hr class="border border-2 border-primary">
    <p>На ваш email адрес была отправлена инструкция по сбросу пароля.</p>
    <p>Если вы ничего не получили, убедитесь, что введеный вами адрес корректен.</p>
</div>
{% endblock %}

templates/users/password_reset_email.html
Кто-то запросил изменение пароля для email-адреса {{ email }}.
Для смены проля перейдите по ссылке: {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
Имя пользователя: {{ user.get_username }}

templates/users/password_reset_form.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 rounded border bg-light border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Забыли пароль?</h2>
  <hr class="border border-2 border-primary">
    <p>Введите email, чтобы сбросить пароль.</p>
    <form method="post">
        <div class="form-outline mb-4">
            <label class="control-label">Email</label>
            <input class="form-control" value="{{ form.email.value|default_if_none:'' }}" name="email" placeholder="" type="email">
        </div>
        <div class="d-flex justify-content-end pt-3">
            <button type="submit" class="btn btn-primary btn-lg ms-2">Подтвердить</button>
        </div>
        {% csrf_token %}
    </form>
</div>
{% endblock %}

templates/users/registration.html
{% extends 'layout/base.html' %}

{% block content %}

<div class="col-3"></div>

<div class="mt-3 mb-3 p-3 col-6 bg-light rounded border border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Регистрация</h2>
  <hr class="border border-2 border-primary">
  <form method="POST" action="{% url 'users:registration' %}">

    {% csrf_token %}

    <div class="row">
      <div class="col-md-6 mb-4">
        <label class="control-label">Имя</label>
        <input class="form-control" value="{{ form.first_name.value|default_if_none:'' }}" name="first_name" placeholder="" type="text">
        {% if 'first_name' in form.errors %}
            {% for error in form.first_name.errors %}
              <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
        {% endif %}
      </div>

      <div class="col-md-6 mb-4">
        <label class="control-label">Фамилия</label>
        <input class="form-control" value="{{ form.last_name.value|default_if_none:'' }}" name="last_name" placeholder="" type="text">
        {% if 'last_name' in form.errors %}
            {% for error in form.last_name.errors %}
              <div class="alert alert-danger alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ error|escape }}</strong>
              </div>
            {% endfor %}
        {% endif %}
      </div>
    </div>

    <div class="form-outline mb-4">
      <label class="control-label">Никнейм</label>
      <input class="form-control" value="{{ form.username.value|default_if_none:'' }}" name="username" placeholder="" type="text">
      {% if 'username' in form.errors %}
          {% for error in form.username.errors %}
            <div class="alert alert-danger alert-dismissable">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
      {% endif %}
    </div>
      
    <div class="form-outline mb-4">
      <label class="control-label">Email</label>
      <input class="form-control" value="{{ form.email.value|default_if_none:'' }}" name="email" placeholder="" type="email">
      {% if 'email' in form.errors %}
        {% for error in form.email.errors %}
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
      
    <div class="form-outline mb-4">
      <label class="control-label">Пароль</label>
      <input class="form-control" name="password1" placeholder="" type="password">
      {% if 'password1' in form.errors %}
        {% for error in form.password1.errors %}
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
      
    <div class="form-outline mb-4">
      <label class="control-label">Повторите пароль</label>
      <input class="form-control" name="password2" placeholder="" type="password">
      {% if 'password2' in form.errors %}
        {% for error in form.password2.errors %}
          <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    
    <div class="d-flex justify-content-end pt-3">
      <button type="submit" class="btn btn-primary btn-lg ms-2" value="Complete Registration!">Зарегистрироваться</button>
    </div>
  </form>
  
</div>
{% endblock %}

templates/users/registration_done.html
{% extends 'layout/base.html' %}

{% block content %}
<div class="col-4"></div>

<div class="mt-3 mb-3 p-3 col-4 rounded border bg-light border-1 row g-0 overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
  <h2 class="text-center">Добро пожаловать, {{ user.username }}!</h2>
  <hr class="border border-2 border-primary">
  <p>Ваш аккаунт был успешно зарегистрирован.</p>
  <p>Теперь вы можете войти.</p>
    <form action="{% url 'users:login' %}">
      <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn btn-primary btn-lg ms-2">Войти</button>
      </div>
    </form>
</div>
{% endblock %}

templates/users/user_settings.html
{% extends "layout/nav_bar.html" %}

{% load static %}
{% load bootstrap5 %}

{% block content %}
<div class="col-10">
  <span>
      <h2 class="mt-3 p-3 border bg-light rounded"><a>Settings - Usernane</a></h2>
  </span>
</div>
<div class="col-10 mt-3">
  <div class="row">
    <div class="col-md-6 mb-4">
      <div class="form-outline">
        <input type="text" id="form3Example1m" class="form-control form-control-lg" />
        <label class="form-label" for="form3Example1m">First name</label>
      </div>
    </div>
    <div class="col-md-6 mb-4">
      <div class="form-outline">
        <input type="text" id="form3Example1n" class="form-control form-control-lg" />
        <label class="form-label" for="form3Example1n">Last name</label>
      </div>
    </div>
  </div>

  <div class="form-outline mb-4">
    <input type="text" id="form3Example8" class="form-control form-control-lg" />
    <label class="form-label" for="form3Example8">Login</label>
  </div>
    
  <div class="form-outline mb-4">
    <input type="text" id="form3Example8" class="form-control form-control-lg" />
    <label class="form-label" for="form3Example8">Email address</label>
  </div>
    
  <div class="d-md-flex justify-content-start align-items-center mb-4 py-2">
    <h6 class="mb-0 me-4">Gender: </h6>
    
    <div class="form-check form-check-inline mb-0 me-4">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender" value="option1" />
      <label class="form-check-label" for="femaleGender">Female</label>
    </div>
    
    <div class="form-check form-check-inline mb-0 me-4">
      <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender"value="option2" />
      <label class="form-check-label" for="maleGender">Male</label>
    </div>
    
  </div>

  <input type="file" class="form-control" id="customFile" />
  <label class="form-label" for="form3Example90">Upload avatar</label>
    
  <div class="d-flex justify-content-end pt-3">
    <button type="button" class="btn btn-light btn-lg">Reset all</button>
    <button type="button" class="btn btn-warning btn-lg ms-2">Create</button>
  </div>
  
</div>
  
{% endblock %}