apps/notifications/urls.py
from django.urls import path

from . import views

app_name = "notifications"

urlpatterns = [
    path("mark_as_read/<int:id>/", views.mark_as_read_view, name="mark_as_read"),
    path("mark_all_as_read/", views.mark_all_as_read_view, name="mark_all_as_read"),
    path("unread/", views.UnreadNotificationsListView.as_view(), name="unread"),
    path("", views.AllNotificationsListView.as_view(), name="all"),
]

apps/profiles/urls.py
from django.urls import path

from . import views


app_name = "profiles"

urlpatterns = [
    path("edit/", views.profile_edit_view, name="profile_edit"),
    path("<slug:username>/", views.ProfileDetailView.as_view(), name="profile_detail"),
    path(
        "<slug:username>/favorites/",
        views.UserFavoriteQuestionList.as_view(),
        name="favorite_questions",
    ),
]

apps/questions/urls.py
from django.urls import path

from . import views


app_name = "questions"

urlpatterns = [
    path("", views.QuestionsListView.as_view(), name="home"),
    path(
        "questions/popular/", views.PopularQuestionsListView.as_view(), name="popular"
    ),
    path(
        "questions/by_tag/<slug:tag_slug>/",
        views.QuestionsByTagListView.as_view(),
        name="by_tag",
    ),
    path("questions/search/", views.question_search_view, name="search"),
    path("question/<int:pk>/<slug:slug>/", views.QuestionView.as_view(), name="detail"),
    path("question/create/", views.QuestionCreateView.as_view(), name="create"),
    path(
        "question/update/<int:pk>/", views.QuestionUpdateView.as_view(), name="update"
    ),
    path(
        "question/delete/<int:pk>/", views.QuestionDeleteView.as_view(), name="delete"
    ),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views
from django.urls import reverse_lazy

from .views import UserRegistrationView

app_name = "users"

urlpatterns = [
    path(
        "login/",
        views.LoginView.as_view(
            redirect_authenticated_user=True,
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
    path(
        "password-change/",
        views.PasswordChangeView.as_view(
            success_url=reverse_lazy("users:password_change_done"),
            template_name="users/password_change_form.html",
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password-reset/",
        views.PasswordResetView.as_view(
            template_name="users/password_reset_form.html",
            email_template_name="users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path("registration/", UserRegistrationView.as_view(), name="registration"),
]

apps/votes/urls.py
from django.urls import path

from apps.questions.models import Question, Answer
from . import models, views


app_name = "votes"

urlpatterns = [
    path(
        "question/like/<int:pk>/",
        views.VoteView.as_view(model=Question, vote_type=models.Vote.LIKE),
        name="question_like",
    ),
    path(
        "question/dislike/<int:pk>/",
        views.VoteView.as_view(model=Question, vote_type=models.Vote.DISLIKE),
        name="question_dislike",
    ),
    path(
        "answer/like/<int:pk>/",
        views.VoteView.as_view(model=Answer, vote_type=models.Vote.LIKE),
        name="answer_like",
    ),
    path(
        "answer/dislike/<int:pk>/",
        views.VoteView.as_view(model=Answer, vote_type=models.Vote.DISLIKE),
        name="answer_dislike",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("apps.users.urls", namespace="users")),
    path("profiles/", include("apps.profiles.urls", namespace="profiles")),
    path("notifications/", include("apps.notifications.urls", namespace="notifications")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
    path("votes/", include("apps.votes.urls", namespace="votes")),
    path("", include("apps.questions.urls", namespace="questions")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

apps/votes/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


class VoteManager(models.Manager):
    """Vote manager"""

    def count_likes(self):
        """Returns value of object likes"""
        likes = (
            self.get_queryset()
            .filter(vote=1)
            .aggregate(models.Count("id"))["id__count"]
            or 0
        )
        return likes

    def count_dislikes(self):
        """Returns value of object dislikes"""
        dislikes = (
            self.get_queryset()
            .filter(vote=-1)
            .aggregate(models.Count("id"))["id__count"]
            or 0
        )
        return dislikes

    def has_user_voted(self, user):
        """Check if the user has voted for the object"""
        return self.get_queryset().filter(user=user).exists()


class Vote(models.Model):
    """Vote model for likes and dislikes"""

    LIKE = 1
    DISLIKE = -1
    VOTES = ((LIKE, "like"), (DISLIKE, "dislike"))

    vote = models.SmallIntegerField(choices=VOTES)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="votes",
    )
    timestamp = models.DateTimeField(default=timezone.now)

    content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, related_name="vote_target"
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    objects = VoteManager()

apps/questions/forms.py
from django import forms

from .models import Answer, Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["title", "tags", "content", "draft"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = [
            "content",
        ]

apps/questions/views.py
from typing import Any

from django.db import models
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.utils.text import slugify
from django.urls import reverse
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Question, Answer
from .forms import AnswerForm, QuestionForm
from .mixins import AuthorRequiredMixin


User = get_user_model()


class QuestionsListView(generic.ListView):
    template_name = "questions/index.html"
    queryset = Question.published.get_all_questions()
    context_object_name = "questions_list"
    paginate_by = 10
    page_title = "Last questions"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = self.page_title
        return context


class QuestionsByTagListView(QuestionsListView):
    page_title = "Questions tagged #"

    def get_queryset(self) -> QuerySet[Question]:
        tag_slug = self.kwargs.get("tag_slug")
        return Question.published.get_tagged_questions(tag_slug)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["page_title"] = f"{self.page_title}{self.kwargs.get('tag_slug')}"
        return context


class PopularQuestionsListView(QuestionsListView):
    queryset = Question.published.get_popular_questions()
    page_title = "Popular questions"


class QuestionDetailView(generic.DetailView):
    template_name = "questions/question_detail.html"
    model = Question
    context_object_name = "question"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["form"] = AnswerForm()
        question = self.get_object()
        context["answers"] = Question.published.get_question_answers(question)
        context["similar_questions"] = Question.published.get_similar_questions(
            question
        )
        return context


class AnswerFormView(generic.detail.SingleObjectMixin, generic.FormView):
    template_name = "questions/question_detail.html"
    form_class = AnswerForm
    model = Answer

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        self.object = self.get_queryset()
        return super().post(request, *args, **kwargs)


class QuestionView(generic.View):
    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        view = QuestionDetailView.as_view()
        question_id = self.kwargs.get("pk")
        Question.objects.filter(pk=question_id).update(views=models.F("views") + 1)
        return view(request, *args, **kwargs)

    @method_decorator(login_required())
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        view = AnswerFormView.as_view()
        form = AnswerForm(request.POST)
        if form.is_valid():
            question = Question.objects.get(id=self.kwargs["pk"])
            form.instance.author = request.user
            form.instance.question = question
            form.save()
        return view(request, *args, **kwargs)


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = "questions/question_create_form.html"
    form_class = QuestionForm

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        title = form.cleaned_data.get("title")
        form.instance.slug = slugify(title)
        form.instance.author = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        question = self.object
        return reverse(
            "questions:detail", kwargs={"pk": question.id, "slug": question.slug}
        )


class QuestionUpdateView(AuthorRequiredMixin, generic.UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = "questions/question_update_form.html"
    context_object_name = "question"

    def get_success_url(self) -> str:
        return self.get_object().get_absolute_url()


class QuestionDeleteView(AuthorRequiredMixin, generic.DeleteView):
    model = Question
    success_url = "/"
    context_object_name = "question"


@require_GET
def question_search_view(request: HttpRequest) -> HttpResponse:
    results = []
    page_title = "Questions search"
    query = request.GET.get("query")

    if query:
        results = Question.published.search(query)
        page_title = f"Questions that contain {query}."

    return render(
        request,
        "questions/index.html",
        context={"page_title": page_title, "questions_list": results},
    )

apps/votes/views.py
from django.http import JsonResponse, HttpRequest
from django.views import View
from django.shortcuts import get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.db import transaction

from apps.notifications.services import send_vote_notification
from .models import Vote


class VoteView(View):
    model = None
    vote_type = None

    @transaction.atomic
    def post(self, request: HttpRequest, pk: int) -> JsonResponse:
        obj = get_object_or_404(self.model, pk=pk)
        user = request.user

        if obj.votes.has_user_voted(user):
            vote_object = Vote.objects.get(
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.id,
                user=user,
            )
            if vote_object.vote == self.vote_type:
                vote_object.delete()
            else:
                Vote.objects.filter(pk=vote_object.pk).update(vote=self.vote_type)
                send_vote_notification(obj, self.vote_type, request.user)
        else:
            obj.votes.create(user=request.user, vote=self.vote_type)
            send_vote_notification(obj, self.vote_type, request.user)

        data = {
            "vote_type": self.vote_type,
            "total_likes": obj.votes.count_likes(),
            "total_dislikes": obj.votes.count_dislikes(),
        }

        return JsonResponse(data)

templates/layout/answer_form.html
<div class="card-footer py-3 border-0">
    <div class="d-flex flex-start w-100">

      <img class="rounded-circle shadow-1-strong me-3"
        src="{{request.user.profile.get_profile_image}}" alt="avatar" width="40"
        height="40" />

      <div class="form-outline w-100">

        <form action="{% url 'questions:detail' question.pk question.slug %}" method="post">
            {% csrf_token %}
            <textarea name="content" class="form-control" id="content" rows="4"
            style="background: #fff;" placeholder="Введите ответ..."></textarea>
            <div class="float-end mt-2 pt-1">
                <button type="submit" id="send-answer" class="btn btn-primary rounded btn-sm">Ответить</button>
            </div>
        </form>

      </div>
    </div>
</div>

templates/layout/answers.html
{% load static %}

<div class="container mt-3">
    <div class="row d-flex justify-content-left">
        <div class="">
            <div class="card">
                {% if request.user.is_authenticated %}
                    {% include 'layout/answer_form.html' with question=question %}
                {% endif %}
                <div id="answers-list">
                    {% for answer in answers %}
                    <div class="card-body border rounded">
                        <div class="d-flex flex-start align-items-center">
                            <img class="rounded-circle shadow-1-strong me-3"
                            src="{{ answer.author.profile.get_profile_image }}" alt="avatar" width="60"
                            height="60" />
                            <div>
                            <h6 class="fw-bold text-primary mb-1">
                                <a href="{{ answer.author.profile.get_absolute_url }}">{{answer.author}}</a>
                            </h6>
                            <p class="text-muted small mb-0">
                                Опубликовано - {{answer.date_published|date:"d-m-Y"}}
                            </p>
                            </div>
                        </div>
        
                        <p class="mt-3 mb-4 pb-2">
                            {{ answer.content }}
                        </p>
                        <div id="votes">
                            {% include 'layout/votes.html' with obj=answer type='answer' %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {{question.id|json_script:"questionId"}}
</div>

<script src="{% static 'js/answers_socket.js' %}"></script>

templates/layout/base.html
{% load static %}
{% load bootstrap5 %}
{% load questions_tags %}

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" ></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  {% bootstrap_css %}
</head>

<body style="background-color: #edeef0;">
    {% include "layout/nav_bar.html" %}
    <main class="flex-shrink-0">
        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </main>
    {{request.user.username|json_script:"username"}}
    <script src="https://use.fontawesome.com/fe459689b4.js"></script>
    <script src="{% static 'js/csrf_token.js' %}"></script>
    <script src="{% static 'js/notification_socket.js' %}"></script>
</body>
</html>

templates/layout/nav_bar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'questions:home' %}">ASK</a>

    <form action="{% url 'questions:search' %}" class="input-group" style="width: 400px">
      <input name="query" type="search" class="form-control" placeholder="Найти вопрос..." aria-label="Search" />
      <button class="btn btn-outline-primary" type="submit" data-mdb-ripple-color="dark" style="padding: .45rem 1.5rem .35rem;">
        Поиск
      </button>
    </form>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'questions:popular' %}">
            Популярные вопросы
          </a>
        </li>
        {% if request.user.is_authenticated %}
          <a
            class="nav-link d-flex align-items-center"
            href="{% url 'profiles:profile_detail' request.user.username %}"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            <img
              src="{{request.user.profile.get_profile_image}}"
              class="rounded-circle"
              height="30"
              width="30"
              alt=""
              loading="lazy"
            />
          </a>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              Уведомления (<small id="notification-counter"></small>)
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'notifications:all' %}">Все уведомления</a></li>
              <li><a id="read-all" class="dropdown-item" href="">Прочитать все</a></li>
              <li id="push-notification-list" class="overflow-scroll" style="max-height: 300px;"></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              {{request.user.username}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="{{ request.user.profile.get_absolute_url }}">Профиль</a></li>
              <li><a class="dropdown-item" href="{% url 'profiles:profile_edit' %}">Редактировать</a></li>
              <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Сменить пароль</a></li>
              <div class="dropdown-divider"></div>
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
            </ul>
          </li>>
        {% else %}
          <li class="nav-item">
            <a class="nav-link d-flex flex-column text-center" aria-current="page" href="{% url 'users:registration' %}"><span class="small">Зарегистрироваться</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link d-flex flex-column text-center" aria-current="page" href="{% url 'users:login' %}"><span class="small">Войти</span></a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/layout/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>

templates/layout/popular_tags.html
{% load questions_tags %}
<div class="position-fixed">
    <h2 class="mt-3 p-3 border text-light bg-secondary bg-gradient rounded text-center" style="width: 20rem;">Популярные теги</h2>
    <div class="p-3 border text-light bg-light rounded" style="max-width: 20rem;">
        {% popular_tags_list as popular_tags_list %}
            {% for tag in popular_tags_list %}
            <div class="d-flex flex-row" style="padding: .25rem 0rem .25rem;">
                <div class="d-flex align-items-center">
                    <form action="{% url 'questions:by_tag' tag.slug %}">
                        <button class="btn btn-outline-primary" type="submit" data-mdb-ripple-color="dark" style="padding: .15rem 1rem .1rem;">
                            {{ tag.name }}
                        </button>
                    </form>
                </div>
                <div class="d-flex align-items-start text-dark" style="padding: .0rem 1rem .0rem;">
                    x
                </div>
                <div class="d-flex align-items-center text-dark">
                    {{ tag.total_questions }}
                </div>
            </div>
            {% endfor %}
    </div>
</div>

templates/layout/questions.html
{% load questions_tags %}

{% for question in questions %}
<div class="row g-0 border bg-light rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
    <div class="col-8 p-3 d-flex flex-column align-items-start bd-highlight mb-3">

        <div class="mb-auto d-flex flex-column bd-highlight" style="padding: .0rem .0rem .0rem 0.6rem ;">
            <h3 class="mb-1"><a href="{{ question.get_absolute_url }}" class="href">{{ question.title }}</a></h3>
            <div class="mb-1 text-muted">
                <div>Опубликовано - {{ question.date_published|date:"d-m-Y" }}</div>
            </div>
            <div class="d-flex flex-row">
                <p>
                    {{ question.content|truncatechars:170 }}
                </p>
            </div>
        </div>

        <div class="bd-highlight">

            {% include 'layout/votes.html' with obj=question type='question' %}

            <div class="d-flex flex-row justify-content-left">
                {% for tag in question.tags.all %}
                <div class="d-flex align-items-start" style="padding: .8rem .2rem .0rem .6rem;">
                    <form action="{% url 'questions:by_tag' tag.slug %}">
                        <button class="btn btn-outline-primary" type="submit" data-mdb-ripple-color="dark" style="padding: .15rem .5rem .1rem; float: left;">
                            {{ tag.name }}
                        </button>
                    </form>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>

    <div class="col-4 border bg-light">
        <div class="p-3 d-flex flex-column justify-content-center">
            <div class="p-2 d-flex justify-content-center">
                <img class="rounded-circle" src="{{question.author.profile.get_profile_image}}" alt="profile_image" width="200" height="200">
            </div>
            <a class="list-group-item list-group-item-action text-center rounded" href="{% url 'profiles:profile_detail' question.author.username %}">{{ question.author.username }}</a>
        </div>
    </div>

</div>

{% empty %}
Вопросов не найдено
{% endfor %}

{% include 'layout/pagination.html' with page=page_obj %}

templates/layout/questions_side_menu.html
<div class="position-fixed">
    <span>
      <h2 class="mt-3 p-3 border text-light bg-secondary bg-gradient rounded" style="width: 20rem;">
        <a>Похожие вопросы</a>
      </h2>
    </span>
    {% for question in questions %}
    <div class="card text-dark bg-light mb-3" style="width: 20rem;">
        <div class="row g-0">
            <div class="col-md-3 d-flex flex-column justify-content-center">
                <div class="d-flex justify-content-center">
                    <img src="{{ question.author.profile.get_profile_image }}" class="rounded-circle p-1" alt="..." width="65" height="65" >
                </div>
                <div class="d-flex justify-content-center">
                    <p class="card-text">
                        <a href="{{ question.author.profile.get_absolute_url}}">{{ question.author.username }}</a>
                    </p>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ question.get_absolute_url }}" class="href">{{ question.title }}</a></h5>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

templates/layout/votes.html
{% load static %}

<div class="d-flex flex-row justify-content-left">
    <div class="d-flex align-items-start" style="padding: .9rem 0rem .0rem .0rem;">
        <form class="vote-form" data-message-id="{{obj.id}}">
            {% csrf_token %}
            <button data-type="{{type}}" data-action="like" type="submit" class="btn">
                <i class="fa fa-thumbs-up fa-lg" aria-hidden="true">
                    <span class="like-counter" id="total-likes{{obj.id}}">{{obj.likes_count}}</span>
                </i>
            </button>
        </form>
    </div>

    <div class="d-flex align-items-start" style="padding: .9rem 0rem .0rem .0rem;">
        <form class="vote-form" data-message-id="{{obj.id}}">
            {% csrf_token %}
            <button data-type="{{type}}" data-action="dislike" type="submit" class="btn">
                <i class="fa fa-thumbs-down fa-lg" aria-hidden="true">
                    <span class="dislike-counter" id="total-dislikes{{obj.id}}">{{ obj.dislikes_count}}</span>
                </i>
            </button>
        </form>
    </div>
</div>

{% if request.user.is_authenticated %}
    <script src="{% static 'js/votes.js' %}"></script>
{% endif %}